apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ template "middleware.fullname" . }}
  annotations:
    {{- with .Values.ingressRoute.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    app.kubernetes.io/name: {{ template "middleware.name" . }}
    helm.sh/chart: {{ template "middleware.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}    
spec:
  {{- with .Values.spec }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
